github:
  description: Apache Flink Website
  homepage: https://flink.apache.org/
  labels:
    - flink
    - big-data
    - scala
    - java
    - website
    - hugo

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
publish:
  whoami: asf-site

staging:
  profile:
  whoami: asf-staging
