github:
  description: Apache Flink Website
  homepage: https://flink.apache.org/
  labels:
    - flink
    - big-data
    - scala
    - java
    - website
    - hugo

publish:
  whoami: asf-site

staging:
  profile: ~
  whoami:  asf-staging